package com.order.create.dto;

import jakarta.validation.constraints.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.util.List;

/**
 * Request DTO for creating a new order.
 * traceId is optional — if not provided it will be auto-generated by TraceFilter.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class CreateOrderRequest {

    @NotBlank(message = "Customer ID is required")
    private String customerId;

    @NotBlank(message = "Customer name is required")
    private String customerName;

    @NotBlank(message = "Customer email is required")
    @Email(message = "Invalid email format")
    private String customerEmail;

    @NotEmpty(message = "Order items cannot be empty")
    private List<OrderItemRequest> items;

    /** Optional: upstream traceId — if null, a new one is generated by TraceFilter */
    private String traceId;

    /** Optional: correlation ID (e.g. session id, batch id) */
    private String correlationId;
}
