spring.application.name=createorder
server.port=8081
spring.datasource.url=jdbc:h2:mem:createorderdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
# Enhancement #2 — InventoryService URL
inventory.service.url=http://localhost:8085
management.endpoints.web.exposure.include=health,info,metrics
logging.level.com.createorder=INFO
